gesdinet_jwt_refresh_token:
    path: /token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

login:
    path: /token/get
    methods: POST

register:
    path: /token/register
    controller: App\Controller\RegisterController::register
    methods: POST
